import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import NextAuthSessionProvider from '@/app/provider/sessionProvider'

const roboto = Roboto({
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextAuthSessionProvider>
          <div className="antialiased">{children}</div>
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
